name: hr_client_front

services:
  hr_client_front:
    image: $DOCKER_IMAGE:$TAG
    container_name: hr_client_front
    restart: unless-stopped
    networks:
      - hr_client

  hr_client_front_nginx:
    image: nginx:alpine
    container_name: hr_client_front_nginx
    restart: unless-stopped
    ports:
      - "91:80"
    networks:
      - hr_client
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf


