name: recruit_front

networks:
  hr_client_api-net:
    external: true

volumes:
  code:
    name: recruit_front

services:
  recruit_front:
    image: $DOCKER_IMAGE:$TAG
    container_name: recruit_front
    restart: unless-stopped
    networks:
      - hr_client_api-net
    volumes:
      - code:/app


  recruit_front_nginx:
    image: recruit_front_nginx:$TAG
    container_name: recruit_front_nginx
    restart: unless-stopped
    ports:
      - "91:80"
    networks:
      - hr_client_api-net
    volumes:
      - code:/var/www:ro 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf


